version: "3"

services:
  serve:
    build:
      context: ./nginx
    container_name: serve
    restart: always
    networks:
      - fc-network
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s node server.js
    networks:
      - fc-network
    depends_on:
      - db

  db:
    build:
      context: ./mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fc-network

networks:
  fc-network:
    driver: bridge
